url: https://www.disarm.io
baseurl:

# Site settings
title: DiSARM
email: hello@disarm.io
description: "Data-driven decision making platform for malaria"
host: 0.0.0.0

# TODO: Install jekyll-paginate gem
paginate: 5
paginate_path: "/progress/page:num/"

collections:
  progress_updates:
    output: true

# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-admin
  - jekyll-paginate
