url: https://www.disarm.io
baseurl:

# Site settings
title: DiSARM
email: hello@disarm.io
description: "Data-driven decision making platform for malaria"
host: 0.0.0.0

image_root_url: https://res.cloudinary.com/disarm/image/upload/
image_account : disarm-website

collections:
  partners:
    output: true
  team_members:
    output: true
  progress_updates:
    output: true

# Build settings
markdown: kramdown
permalink: pretty

prose:
  metadata:
    _progress_updates:
      - name: title # Automated risk modelling is working
        field:
          label: Update title
          element: text
          type: text
      - name: layout # post
        field:
          element: hidden
          value: post
      - name: post_date # '2016-11-03'
        field:
          label: Date of post
          element: text
          type: text
      - name: image # Outline_Of_IRS_Work
        field:
          label: Selected image
          element: text
          type: text