url: https://www.disarm.io
baseurl: 

# Site settings
title: DiSARM
email: hello@disarm.io
description: "Data-driven decision making platform for malaria"

collections:
  - progress_updates

# Build settings
markdown: kramdown
permalink: pretty