url: https://www.disarm.io
baseurl:

# Site settings
title: DiSARM
email: hello@disarm.io
description: "Data-driven decision making platform for malaria"
host: 0.0.0.0

image_root_url: https://res.cloudinary.com/disarm/image/upload/
image_account : disarm-website

collections:
  partners:
    output: true
  team_members:
    output: true
  progress_updates:
    output: true

# Build settings
markdown: kramdown
permalink: pretty

