url: https://www.disarm.io
baseurl: 

# Site settings
title: DiSARM
email: hello@disarm.io
description: "[Mlandvo - can you fill this in?!]"

collections:
  - progress_updates

# Build settings
markdown: kramdown
permalink: pretty